//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registertaion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbenrollementEntities : DbContext
    {
        public dbenrollementEntities()
            : base("name=dbenrollementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbcourse> tbcourses { get; set; }
        public virtual DbSet<tblregisteration> tblregisterations { get; set; }
        public virtual DbSet<tbstudent> tbstudents { get; set; }
    }
}
