//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registertaion
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblregisteration
    {
        public int id { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> course_id { get; set; }
    
        public virtual tbcourse tbcourse { get; set; }
        public virtual tbstudent tbstudent { get; set; }
    }
}
